
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Receipt, Stethoscope, HeartPulse, ShieldPlus, CheckCircle2, PartyPopper } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { db } from "@/lib/firebase"; // Import Firebase db
import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import type { Turn } from '@/types/turn'; // Import Turn type from new location
import { useToast } from "@/hooks/use-toast";


const services: { value: string; label: string; icon: LucideIcon, prefix: string }[] = [
  { value: "facturacion", label: "Facturación", icon: Receipt, prefix: "F" },
  { value: "citas_medicas", label: "Citas Médicas", icon: Stethoscope, prefix: "C" },
  { value: "famisanar", label: "Famisanar", icon: HeartPulse, prefix: "FS" }, // Changed prefix to avoid conflict
  { value: "nueva_eps", label: "Nueva EPS", icon: ShieldPlus, prefix: "N" },
];

const formSchema = z.object({
  service: z.string({ required_error: "Por favor seleccione un servicio." }),
  idNumber: z.string().min(1, "El número de cédula es requerido.").regex(/^[0-9a-zA-Z]+$/, "Solo se permiten números y letras."),
  isSenior: z.boolean().default(false),
  isPregnant: z.boolean().default(false),
  isDisabled: z.boolean().default(false),
  isNone: z.boolean().default(false),
});

type FormValues = z.infer<typeof formSchema>;

// Helper to generate a somewhat unique numeric suffix for turn numbers
// This is a simplified approach. For a robust system, turn number generation should be managed server-side or with more sophisticated client-side logic.
const generateTurnSuffix = async () => {
  // This is a placeholder. In a real scenario, you might query Firestore for the last turn number of a given prefix.
  // For now, using a timestamp-based suffix for simplicity.
  return Date.now().toString().slice(-3); 
};


export default function TurnForm() {
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [submittedTurnNumber, setSubmittedTurnNumber] = useState<string | null>(null);
  const [submittedServiceLabel, setSubmittedServiceLabel] = useState<string | null>(null);
  const [submittedIdNumber, setSubmittedIdNumber] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { toast } = useToast();


  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      service: "",
      idNumber: "",
      isSenior: false,
      isPregnant: false,
      isDisabled: false,
      isNone: true, // Default to Ninguna
    },
  });

  const { watch, setValue, reset } = form;
  const isSenior = watch("isSenior");
  const isPregnant = watch("isPregnant");
  const isDisabled = watch("isDisabled");
  const isNone = watch("isNone");

  useEffect(() => {
    if (isNone) {
      setValue("isSenior", false);
      setValue("isPregnant", false);
      setValue("isDisabled", false);
    }
  }, [isNone, setValue]);

  useEffect(() => {
    if (isSenior || isPregnant || isDisabled) {
      setValue("isNone", false);
    }
  }, [isSenior, isPregnant, isDisabled, setValue]);

  async function onSubmit(data: FormValues) {
    setIsSubmitting(true);
    const selectedServiceInfo = services.find(s => s.value === data.service);
    if (!selectedServiceInfo) {
      toast({ title: "Error", description: "Servicio no encontrado.", variant: "destructive" });
      setIsSubmitting(false);
      return;
    }

    try {
      const turnSuffix = await generateTurnSuffix();
      const newTurnNumber = `${selectedServiceInfo.prefix}-${turnSuffix.padStart(3, '0')}`;

      const newTurnData: Omit<Turn, 'id' | 'requestedAt'> & { requestedAt: any } = { // id will be auto-generated by Firestore
        turnNumber: newTurnNumber,
        service: selectedServiceInfo.label,
        patientId: `CC ${data.idNumber}`,
        priority: data.isSenior || data.isPregnant || data.isDisabled,
        status: 'pending',
        requestedAt: serverTimestamp(), // Use Firestore server timestamp
      };

      await addDoc(collection(db, "turns"), newTurnData);
      
      setSubmittedTurnNumber(newTurnNumber);
      setSubmittedServiceLabel(selectedServiceInfo.label);
      setSubmittedIdNumber(data.idNumber);
      setIsSubmitted(true);
      toast({ title: "Turno Registrado", description: `Tu turno ${newTurnNumber} ha sido creado.` });
    } catch (error) {
      console.error("Error adding document: ", error);
      toast({ title: "Error", description: "No se pudo registrar el turno. Intente de nuevo.", variant: "destructive" });
    } finally {
      setIsSubmitting(false);
    }
  }

  function handleNewTurn() {
    setIsSubmitted(false);
    setSubmittedTurnNumber(null);
    reset({ 
        service: "",
        idNumber: "",
        isSenior: false,
        isPregnant: false,
        isDisabled: false,
        isNone: true,
    });
  }
  
  const selectedServiceValue = watch("service");
  const currentSelectedService = services.find(s => s.value === selectedServiceValue);

  if (isSubmitted && submittedTurnNumber && submittedServiceLabel && submittedIdNumber) {
    return (
      <Card className="w-full max-w-lg shadow-xl">
        <CardHeader className="text-center">
          <div className="mx-auto bg-accent/30 text-accent-foreground p-3 rounded-full w-fit mb-4">
            <PartyPopper className="h-10 w-10" />
          </div>
          <CardTitle className="text-2xl font-bold">¡Turno Registrado!</CardTitle>
          <CardDescription className="text-muted-foreground">
            Su turno <span className="font-semibold text-primary">{submittedTurnNumber}</span> ha sido procesado exitosamente.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4 text-sm">
          <div className="flex justify-between">
            <span className="font-medium">Servicio:</span>
            <span>{submittedServiceLabel}</span>
          </div>
          <div className="flex justify-between">
            <span className="font-medium">Número de Cédula:</span>
            <span>{submittedIdNumber}</span>
          </div>
           <p className="text-center text-muted-foreground pt-4">Pronto será llamado. Gracias por su paciencia.</p>
        </CardContent>
        <CardFooter>
          <Button onClick={handleNewTurn} className="w-full bg-primary hover:bg-primary/90">
            Solicitar Nuevo Turno
          </Button>
        </CardFooter>
      </Card>
    );
  }

  return (
    <Card className="w-full max-w-lg shadow-xl">
      <CardHeader>
        <CardTitle className="text-3xl font-bold text-center text-primary-foreground bg-primary -mx-6 -mt-6 p-6 rounded-t-lg">TurnoFacil</CardTitle>
        <CardDescription className="text-center pt-2">
          Seleccione el servicio deseado y complete sus datos para obtener un turno.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
            <FormField
              control={form.control}
              name="service"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Tipo de Servicio</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger className="text-base">
                        {currentSelectedService ? (
                          <div className="flex items-center gap-2">
                            <currentSelectedService.icon className="h-5 w-5 text-muted-foreground" />
                            {currentSelectedService.label}
                          </div>
                        ) : (
                          <span className="text-muted-foreground">Seleccione un servicio</span>
                        )}
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {services.map((service) => (
                        <SelectItem key={service.value} value={service.value} className="text-base">
                          <div className="flex items-center gap-2">
                            <service.icon className="h-5 w-5 text-muted-foreground" />
                            {service.label}
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="idNumber"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Número de Cédula/Identificación</FormLabel>
                  <FormControl>
                    <Input placeholder="Ej: 1234567890" {...field} className="text-base" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormItem>
              <FormLabel>Condiciones Especiales (Opcional)</FormLabel>
              <div className="space-y-3 pt-2">
                {[
                  { name: "isSenior", label: "Adulto Mayor" },
                  { name: "isPregnant", label: "Gestante" },
                  { name: "isDisabled", label: "Discapacitado" },
                  { name: "isNone", label: "Ninguna" },
                ].map((item) => (
                  <FormField
                    key={item.name}
                    control={form.control}
                    name={item.name as keyof FormValues}
                    render={({ field }) => (
                      <FormItem className="flex flex-row items-center space-x-3 space-y-0 p-3 border rounded-md hover:bg-accent/50 transition-colors">
                        <FormControl>
                          <Checkbox
                            checked={field.value as boolean}
                            onCheckedChange={field.onChange}
                            aria-label={item.label}
                            disabled={
                                (item.name === "isSenior" && (isPregnant || isDisabled)) ||
                                (item.name === "isPregnant" && (isSenior || isDisabled)) ||
                                (item.name === "isDisabled" && (isSenior || isPregnant)) ||
                                (item.name !== "isNone" && isNone)
                            }
                          />
                        </FormControl>
                        <FormLabel className={`font-normal text-base m-0! cursor-pointer ${
                            ((item.name === "isSenior" && (isPregnant || isDisabled)) ||
                            (item.name === "isPregnant" && (isSenior || isDisabled)) ||
                            (item.name === "isDisabled" && (isSenior || isPregnant)) ||
                            (item.name !== "isNone" && isNone)) ? 'text-muted-foreground opacity-50 cursor-not-allowed' : ''
                        }`}>
                          {item.label}
                        </FormLabel>
                      </FormItem>
                    )}
                  />
                ))}
              </div>
               <FormMessage>{form.formState.errors.isNone?.message || form.formState.errors.isSenior?.message /* etc. or a general message */}</FormMessage>
            </FormItem>
            
            <Button type="submit" className="w-full text-lg py-6 bg-accent text-accent-foreground hover:bg-accent/90" disabled={isSubmitting}>
              {isSubmitting ? "Registrando..." : "Solicitar Turno"}
              {!isSubmitting && <CheckCircle2 className="ml-2 h-5 w-5" />}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
